management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    git:
      enabled: true            #  id "com.gorylenko.gradle-git-properties" version "2.4.1"  ? ????? ?? ?? ???? ??? ??? ???? ???.
    env:
      enabled: true
    build:
      enabled: true           # ??? build.gradle ? springBoot { buildInfo() } ? ????? ??.
  endpoint:
    shutdown:
      enabled: true        # shutdown ? ??? ???? ?
    health:
      show-components: always
  #      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"        #?? ??? ?????? ?
  server:
    port: 8080




# info ?? ?????? ??? ????.
info:
  app:
    name: brunosong-actuator

logging:
  level:
    hello.contoller: debug


server:
  tomcat:
    mbeanregistry:
      enabled: true
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: